/*---------------------------------------------------------
 * Autogenerated -- do not modify
 * Generated from C:/Users/Rudolf/source/repos/STUBA-rupr/open62541-i4Component/examples/nodeset/stm32-EnvSensor-AASX041_part1.csv with script C:/Users/Rudolf/source/repos/STUBA-rupr/open62541-i4Component/tools/generate_nodeid_header.py
 *-------------------------------------------------------*/

#ifndef UA_NODEIDS_I4AAS_H_
#define UA_NODEIDS_I4AAS_H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from the ``C:/Users/Rudolf/source/repos/STUBA-rupr/open62541-i4Component/examples/nodeset/stm32-EnvSensor-AASX041_part1.csv`` file */

#define UA_I4AASID_IDTYPE_1  1 /* UAVariable */
#define UA_I4AASID_ID_2  2 /* UAVariable */
#define UA_I4AASID_1:AASIRDICONCEPTDESCRIPTIONTYPE_3  3 /* UAObjectType */
#define UA_I4AASID_CATEGORY_58  58 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_59  59 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_60  60 /* UAObject */
#define UA_I4AASID_ISCASEOF_61  61 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION_62  62 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360_63  63 /* UAObject */
#define UA_I4AASID_1:AASURICONCEPTDESCRIPTIONTYPE_4  4 /* UAObjectType */
#define UA_I4AASID_CATEGORY_64  64 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_65  65 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_66  66 /* UAObject */
#define UA_I4AASID_ISCASEOF_67  67 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION_68  68 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360_69  69 /* UAObject */
#define UA_I4AASID_1:AASCUSTOMCONCEPTDESCRIPTIONTYPE_5  5 /* UAObjectType */
#define UA_I4AASID_CATEGORY_70  70 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_71  71 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_72  72 /* UAObject */
#define UA_I4AASID_ISCASEOF_73  73 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION_74  74 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360_75  75 /* UAObject */
#define UA_I4AASID_IDENTIFICATION_6  6 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_7  7 /* UAObject */
#define UA_I4AASID_KEYS_8  8 /* UAVariable */
#define UA_I4AASID_CATEGORY_9  9 /* UAVariable */
#define UA_I4AASID_PREFERREDNAME_16  16 /* UAVariable */
#define UA_I4AASID_SHORTNAME_17  17 /* UAVariable */
#define UA_I4AASID_UNIT_18  18 /* UAVariable */
#define UA_I4AASID_UNITID_19  19 /* UAObject */
#define UA_I4AASID_SOURCEOFDEFINITION_20  20 /* UAVariable */
#define UA_I4AASID_SYMBOL_21  21 /* UAVariable */
#define UA_I4AASID_DATATYPE_22  22 /* UAVariable */
#define UA_I4AASID_DEFINITION_23  23 /* UAVariable */
#define UA_I4AASID_VALUEFORMAT_24  24 /* UAVariable */
#define UA_I4AASID_SEMANTICID_25  25 /* UAObject */
#define UA_I4AASID_TYPE_26  26 /* UAVariable */
#define UA_I4AASID_VALUE_27  27 /* UAVariable */
#define UA_I4AASID_VALUEID_28  28 /* UAObject */
#define UA_I4AASID_CATEGORY_29  29 /* UAVariable */
#define UA_I4AASID_SEMANTICID_30  30 /* UAObject */
#define UA_I4AASID_KIND_31  31 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION_32  32 /* UAObject */
#define UA_I4AASID_QUALIFIER_33  33 /* UAObject */
#define UA_I4AASID_CATEGORY_34  34 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_35  35 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_36  36 /* UAObject */
#define UA_I4AASID_SEMANTICID_37  37 /* UAObject */
#define UA_I4AASID_KIND_38  38 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION_39  39 /* UAObject */
#define UA_I4AASID_QUALIFIER_40  40 /* UAObject */
#define UA_I4AASID_SUBMODELELEMENT_41  41 /* UAObject */
#define UA_I4AASID_VALUETYPE_42  42 /* UAVariable */
#define UA_I4AASID_VALUE_43  43 /* UAVariable */
#define UA_I4AASID_ALLOWDUPLICATES_44  44 /* UAVariable */
#define UA_I4AASID_MIMETYPE_45  45 /* UAVariable */
#define UA_I4AASID_VALUE_46  46 /* UAVariable */
#define UA_I4AASID_FILE_47  47 /* UAObject */
#define UA_I4AASID_MIMETYPE_48  48 /* UAVariable */
#define UA_I4AASID_VALUE_49  49 /* UAVariable */
#define UA_I4AASID_VALUE_50  50 /* UAObject */
#define UA_I4AASID_FIRST_51  51 /* UAObject */
#define UA_I4AASID_SECOND_52  52 /* UAObject */
#define UA_I4AASID_OPERATION_53  53 /* UAMethod */
#define UA_I4AASID_IN_54  54 /* UAObject */
#define UA_I4AASID_OUT_55  55 /* UAObject */
#define UA_I4AASID_CATEGORY_56  56 /* UAVariable */
#define UA_I4AASID_DICTIONARYENTRY_57  57 /* UAObject */
#define UA_I4AASID_CATEGORY_76  76 /* UAVariable */
#define UA_I4AASID_SEMANTICID_77  77 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION_78  78 /* UAObject */
#define UA_I4AASID_CONTAINEDELEMENT_79  79 /* UAObject */
#define UA_I4AASID_CATEGORY_80  80 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_81  81 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_82  82 /* UAObject */
#define UA_I4AASID_KIND_83  83 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION_84  84 /* UAObject */
#define UA_I4AASID_ASSETIDENTIFICATIONMODEL_85  85 /* UAObject */
#define UA_I4AASID_CATEGORY_86  86 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION_87  87 /* UAObject */
#define UA_I4AASID_ADMINISTRATION_88  88 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION_89  89 /* UAObject */
#define UA_I4AASID_DERIVEDFROM_90  90 /* UAObject */
#define UA_I4AASID_ASSET_91  91 /* UAObject */
#define UA_I4AASID_VIEW_92  92 /* UAObject */
#define UA_I4AASID_SUBMODEL_93  93 /* UAObject */
#define UA_I4AASID_CONCEPTDICTIONARY_94  94 /* UAObject */
#define UA_I4AASID_1:AASIDENTIFIERTYPE_1000  1000 /* UAObjectType */
#define UA_I4AASID_1:AASADMINISTRATIVEINFORMATIONTYPE_1001  1001 /* UAObjectType */
#define UA_I4AASID_1:AASQUALIFIERTYPE_1002  1002 /* UAObjectType */
#define UA_I4AASID_1:AASREFERENCETYPE_1005  1005 /* UAObjectType */
#define UA_I4AASID_1:AASSUBMODELTYPE_1007  1007 /* UAObjectType */
#define UA_I4AASID_1:AASSUBMODELELEMENTTYPE_1008  1008 /* UAObjectType */
#define UA_I4AASID_1:AASPROPERTYTYPE_1009  1009 /* UAObjectType */
#define UA_I4AASID_1:AASSUBMODELELEMENTCOLLECTIONTYPE_1010  1010 /* UAObjectType */
#define UA_I4AASID_1:AASSUBMODELELEMENTORDEREDCOLLECTIONTYPE_1011  1011 /* UAObjectType */
#define UA_I4AASID_1:AASFILETYPE_1013  1013 /* UAObjectType */
#define UA_I4AASID_1:AASBLOBTYPE_1015  1015 /* UAObjectType */
#define UA_I4AASID_1:AASREFERENCEELEMENTTYPE_1016  1016 /* UAObjectType */
#define UA_I4AASID_1:AASRELATIONSHIPELEMENTTYPE_1017  1017 /* UAObjectType */
#define UA_I4AASID_1:OPERATIONVARIABLETYPE_1018  1018 /* UAObjectType */
#define UA_I4AASID_1:AASOPERATIONTYPE_1019  1019 /* UAObjectType */
#define UA_I4AASID_1:AASCONCEPTDICTIONARYTYPE_1020  1020 /* UAObjectType */
#define UA_I4AASID_1:AASVIEWTYPE_1022  1022 /* UAObjectType */
#define UA_I4AASID_1:AASASSETTYPE_1023  1023 /* UAObjectType */
#define UA_I4AASID_1:AASASSETADMINISTRATIONSHELLTYPE_1024  1024 /* UAObjectType */
#define UA_I4AASID_1:IAASIDENTIFIABLETYPE_2000  2000 /* UAObjectType */
#define UA_I4AASID_1:IAASREFERABLETYPE_2001  2001 /* UAObjectType */
#define UA_I4AASID_1:AASDATASPECIFICATIONTYPE_3000  3000 /* UAObjectType */
#define UA_I4AASID_1:AASDATASPECIFICATIONIEC61360TYPE_3001  3001 /* UAObjectType */
#define UA_I4AASID_AASREFERENCE_4000  4000 /* UAReferenceType */
#endif /* UA_NODEIDS_I4AAS_H_ */ 
