/*---------------------------------------------------------
 * Autogenerated -- do not modify
 * Generated from C:/Projects/open62541-i4Component/examples/nodeset/EcI4.0-STM32_rA03_Nodeset2.csv with script C:/Projects/open62541-i4Component/tools/generate_nodeid_header.py
 *-------------------------------------------------------*/

#ifndef UA_NODEIDS_I4AAS_H_
#define UA_NODEIDS_I4AAS_H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from the ``C:/Projects/open62541-i4Component/examples/nodeset/EcI4.0-STM32_rA03_Nodeset2.csv`` file */

#define UA_I4AASID_IDTYPE 1 /* UAVariable */
#define UA_I4AASID_ID 2 /* UAVariable */
#define UA_I4AASID_AASIRDICONCEPTDESCRIPTIONTYPE 3 /* UAObjectType */
#define UA_I4AASID_CATEGORY 58 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 59 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 60 /* UAObject */
#define UA_I4AASID_ISCASEOF 61 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION 62 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360 63 /* UAObject */
#define UA_I4AASID_AASURICONCEPTDESCRIPTIONTYPE 4 /* UAObjectType */
#define UA_I4AASID_CATEGORY 64 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 65 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 66 /* UAObject */
#define UA_I4AASID_ISCASEOF 67 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION 68 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360 69 /* UAObject */
#define UA_I4AASID_AASCUSTOMCONCEPTDESCRIPTIONTYPE 5 /* UAObjectType */
#define UA_I4AASID_CATEGORY 70 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 71 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 72 /* UAObject */
#define UA_I4AASID_ISCASEOF 73 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION 74 /* UAObject */
#define UA_I4AASID_DATASPECIFICATIONIEC61360 75 /* UAObject */
#define UA_I4AASID_IDENTIFICATION 6 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 7 /* UAObject */
#define UA_I4AASID_KEYS 8 /* UAVariable */
#define UA_I4AASID_CATEGORY 9 /* UAVariable */
#define UA_I4AASID_PREFERREDNAME 16 /* UAVariable */
#define UA_I4AASID_SHORTNAME 17 /* UAVariable */
#define UA_I4AASID_UNIT 18 /* UAVariable */
#define UA_I4AASID_UNITID 19 /* UAObject */
#define UA_I4AASID_SOURCEOFDEFINITION 20 /* UAVariable */
#define UA_I4AASID_SYMBOL 21 /* UAVariable */
#define UA_I4AASID_DATATYPE 22 /* UAVariable */
#define UA_I4AASID_DEFINITION 23 /* UAVariable */
#define UA_I4AASID_VALUEFORMAT 24 /* UAVariable */
#define UA_I4AASID_SEMANTICID 25 /* UAObject */
#define UA_I4AASID_TYPE 26 /* UAVariable */
#define UA_I4AASID_VALUE 27 /* UAVariable */
#define UA_I4AASID_VALUEID 28 /* UAObject */
#define UA_I4AASID_CATEGORY 29 /* UAVariable */
#define UA_I4AASID_SEMANTICID 30 /* UAObject */
#define UA_I4AASID_KIND 31 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION 32 /* UAObject */
#define UA_I4AASID_QUALIFIER 33 /* UAObject */
#define UA_I4AASID_CATEGORY 34 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 35 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 36 /* UAObject */
#define UA_I4AASID_SEMANTICID 37 /* UAObject */
#define UA_I4AASID_KIND 38 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION 39 /* UAObject */
#define UA_I4AASID_QUALIFIER 40 /* UAObject */
#define UA_I4AASID_SUBMODELELEMENT 41 /* UAObject */
#define UA_I4AASID_VALUETYPE 42 /* UAVariable */
#define UA_I4AASID_VALUE 43 /* UAVariable */
#define UA_I4AASID_ALLOWDUPLICATES 44 /* UAVariable */
#define UA_I4AASID_MIMETYPE 45 /* UAVariable */
#define UA_I4AASID_VALUE 46 /* UAVariable */
#define UA_I4AASID_FILE 47 /* UAObject */
#define UA_I4AASID_MIMETYPE 48 /* UAVariable */
#define UA_I4AASID_VALUE 49 /* UAVariable */
#define UA_I4AASID_VALUE 50 /* UAObject */
#define UA_I4AASID_FIRST 51 /* UAObject */
#define UA_I4AASID_SECOND 52 /* UAObject */
#define UA_I4AASID_OPERATION 53 /* UAMethod */
#define UA_I4AASID_IN 54 /* UAObject */
#define UA_I4AASID_OUT 55 /* UAObject */
#define UA_I4AASID_CATEGORY 56 /* UAVariable */
#define UA_I4AASID_DICTIONARYENTRY 57 /* UAObject */
#define UA_I4AASID_CATEGORY 76 /* UAVariable */
#define UA_I4AASID_SEMANTICID 77 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION 78 /* UAObject */
#define UA_I4AASID_CONTAINEDELEMENT 79 /* UAObject */
#define UA_I4AASID_CATEGORY 80 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 81 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 82 /* UAObject */
#define UA_I4AASID_KIND 83 /* UAVariable */
#define UA_I4AASID_DATASPECIFICATION 84 /* UAObject */
#define UA_I4AASID_ASSETIDENTIFICATIONMODEL 85 /* UAObject */
#define UA_I4AASID_CATEGORY 86 /* UAVariable */
#define UA_I4AASID_IDENTIFICATION 87 /* UAObject */
#define UA_I4AASID_ADMINISTRATION 88 /* UAObject */
#define UA_I4AASID_DATASPECIFICATION 89 /* UAObject */
#define UA_I4AASID_DERIVEDFROM 90 /* UAObject */
#define UA_I4AASID_ASSET 91 /* UAObject */
#define UA_I4AASID_VIEW 92 /* UAObject */
#define UA_I4AASID_SUBMODEL 93 /* UAObject */
#define UA_I4AASID_CONCEPTDICTIONARY 94 /* UAObject */
#define UA_I4AASID_AASIDENTIFIERTYPE 1000 /* UAObjectType */
#define UA_I4AASID_AASADMINISTRATIVEINFORMATIONTYPE 1001 /* UAObjectType */
#define UA_I4AASID_AASQUALIFIERTYPE 1002 /* UAObjectType */
#define UA_I4AASID_AASREFERENCETYPE 1005 /* UAObjectType */
#define UA_I4AASID_AASSUBMODELTYPE 1007 /* UAObjectType */
#define UA_I4AASID_AASSUBMODELELEMENTTYPE 1008 /* UAObjectType */
#define UA_I4AASID_AASPROPERTYTYPE 1009 /* UAObjectType */
#define UA_I4AASID_AASSUBMODELELEMENTCOLLECTIONTYPE 1010 /* UAObjectType */
#define UA_I4AASID_AASSUBMODELELEMENTORDEREDCOLLECTIONTYPE 1011 /* UAObjectType */
#define UA_I4AASID_AASFILETYPE 1013 /* UAObjectType */
#define UA_I4AASID_AASBLOBTYPE 1015 /* UAObjectType */
#define UA_I4AASID_AASREFERENCEELEMENTTYPE 1016 /* UAObjectType */
#define UA_I4AASID_AASRELATIONSHIPELEMENTTYPE 1017 /* UAObjectType */
#define UA_I4AASID_OPERATIONVARIABLETYPE 1018 /* UAObjectType */
#define UA_I4AASID_AASOPERATIONTYPE 1019 /* UAObjectType */
#define UA_I4AASID_AASCONCEPTDICTIONARYTYPE 1020 /* UAObjectType */
#define UA_I4AASID_AASVIEWTYPE 1022 /* UAObjectType */
#define UA_I4AASID_AASASSETTYPE 1023 /* UAObjectType */
#define UA_I4AASID_AASASSETADMINISTRATIONSHELLTYPE 1024 /* UAObjectType */
#define UA_I4AASID_IAASIDENTIFIABLETYPE 2000 /* UAObjectType */
#define UA_I4AASID_IAASREFERABLETYPE 2001 /* UAObjectType */
#define UA_I4AASID_AASDATASPECIFICATIONTYPE 3000 /* UAObjectType */
#define UA_I4AASID_AASDATASPECIFICATIONIEC61360TYPE 3001 /* UAObjectType */
#define UA_I4AASID_AASREFERENCE 4000 /* UAReferenceType */
#endif /* UA_NODEIDS_I4AAS_H_ */ 
