/*---------------------------------------------------------
 * Autogenerated -- do not modify
 * Generated from C:/Projects/open62541-i4Component/examples/nodeset/OpcUai4aasModel.csv with script C:/Projects/open62541-i4Component/tools/generate_nodeid_header.py
 *-------------------------------------------------------*/

#ifndef UA_NODEIDS_I4AAS__H_
#define UA_NODEIDS_I4AAS__H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from the ``C:/Projects/open62541-i4Component/examples/nodeset/OpcUai4aasModel.csv`` file */

#define UA_I4AAS_ID_IDTYPE 1 /* UAVariable */
#define UA_I4AAS_ID_ID 2 /* UAVariable */
#define UA_I4AAS_ID_AASIRDICONCEPTDESCRIPTIONTYPE 3 /* UAObjectType */
#define UA_I4AAS_ID_CATEGORY 58 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 59 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 60 /* UAObject */
#define UA_I4AAS_ID_ISCASEOF 61 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATION 62 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATIONIEC61360 63 /* UAObject */
#define UA_I4AAS_ID_AASURICONCEPTDESCRIPTIONTYPE 4 /* UAObjectType */
#define UA_I4AAS_ID_CATEGORY 64 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 65 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 66 /* UAObject */
#define UA_I4AAS_ID_ISCASEOF 67 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATION 68 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATIONIEC61360 69 /* UAObject */
#define UA_I4AAS_ID_AASCUSTOMCONCEPTDESCRIPTIONTYPE 5 /* UAObjectType */
#define UA_I4AAS_ID_CATEGORY 70 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 71 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 72 /* UAObject */
#define UA_I4AAS_ID_ISCASEOF 73 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATION 74 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATIONIEC61360 75 /* UAObject */
#define UA_I4AAS_ID_IDENTIFICATION 6 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 7 /* UAObject */
#define UA_I4AAS_ID_KEYS 8 /* UAVariable */
#define UA_I4AAS_ID_CATEGORY 9 /* UAVariable */
#define UA_I4AAS_ID_PREFERREDNAME 16 /* UAVariable */
#define UA_I4AAS_ID_SHORTNAME 17 /* UAVariable */
#define UA_I4AAS_ID_UNIT 18 /* UAVariable */
#define UA_I4AAS_ID_UNITID 19 /* UAObject */
#define UA_I4AAS_ID_SOURCEOFDEFINITION 20 /* UAVariable */
#define UA_I4AAS_ID_SYMBOL 21 /* UAVariable */
#define UA_I4AAS_ID_DATATYPE 22 /* UAVariable */
#define UA_I4AAS_ID_DEFINITION 23 /* UAVariable */
#define UA_I4AAS_ID_VALUEFORMAT 24 /* UAVariable */
#define UA_I4AAS_ID_SEMANTICID 25 /* UAObject */
#define UA_I4AAS_ID_TYPE 26 /* UAVariable */
#define UA_I4AAS_ID_VALUE 27 /* UAVariable */
#define UA_I4AAS_ID_VALUEID 28 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 29 /* UAVariable */
#define UA_I4AAS_ID_SEMANTICID 30 /* UAObject */
#define UA_I4AAS_ID_KIND 31 /* UAVariable */
#define UA_I4AAS_ID_DATASPECIFICATION 32 /* UAObject */
#define UA_I4AAS_ID_QUALIFIER 33 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 34 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 35 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 36 /* UAObject */
#define UA_I4AAS_ID_SEMANTICID 37 /* UAObject */
#define UA_I4AAS_ID_KIND 38 /* UAVariable */
#define UA_I4AAS_ID_DATASPECIFICATION 39 /* UAObject */
#define UA_I4AAS_ID_QUALIFIER 40 /* UAObject */
#define UA_I4AAS_ID_SUBMODELELEMENT 41 /* UAObject */
#define UA_I4AAS_ID_VALUETYPE 42 /* UAVariable */
#define UA_I4AAS_ID_VALUE 43 /* UAVariable */
#define UA_I4AAS_ID_ALLOWDUPLICATES 44 /* UAVariable */
#define UA_I4AAS_ID_MIMETYPE 45 /* UAVariable */
#define UA_I4AAS_ID_VALUE 46 /* UAVariable */
#define UA_I4AAS_ID_FILE 47 /* UAObject */
#define UA_I4AAS_ID_MIMETYPE 48 /* UAVariable */
#define UA_I4AAS_ID_VALUE 49 /* UAVariable */
#define UA_I4AAS_ID_VALUE 50 /* UAObject */
#define UA_I4AAS_ID_FIRST 51 /* UAObject */
#define UA_I4AAS_ID_SECOND 52 /* UAObject */
#define UA_I4AAS_ID_OPERATION 53 /* UAMethod */
#define UA_I4AAS_ID_IN 54 /* UAObject */
#define UA_I4AAS_ID_OUT 55 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 56 /* UAVariable */
#define UA_I4AAS_ID_DICTIONARYENTRY 57 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 76 /* UAVariable */
#define UA_I4AAS_ID_SEMANTICID 77 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATION 78 /* UAObject */
#define UA_I4AAS_ID_CONTAINEDELEMENT 79 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 80 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 81 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 82 /* UAObject */
#define UA_I4AAS_ID_KIND 83 /* UAVariable */
#define UA_I4AAS_ID_DATASPECIFICATION 84 /* UAObject */
#define UA_I4AAS_ID_ASSETIDENTIFICATIONMODEL 85 /* UAObject */
#define UA_I4AAS_ID_CATEGORY 86 /* UAVariable */
#define UA_I4AAS_ID_IDENTIFICATION 87 /* UAObject */
#define UA_I4AAS_ID_ADMINISTRATION 88 /* UAObject */
#define UA_I4AAS_ID_DATASPECIFICATION 89 /* UAObject */
#define UA_I4AAS_ID_DERIVEDFROM 90 /* UAObject */
#define UA_I4AAS_ID_ASSET 91 /* UAObject */
#define UA_I4AAS_ID_VIEW 92 /* UAObject */
#define UA_I4AAS_ID_SUBMODEL 93 /* UAObject */
#define UA_I4AAS_ID_CONCEPTDICTIONARY 94 /* UAObject */
#define UA_I4AAS_ID_AASIDENTIFIERTYPE 1000 /* UAObjectType */
#define UA_I4AAS_ID_AASADMINISTRATIVEINFORMATIONTYPE 1001 /* UAObjectType */
#define UA_I4AAS_ID_AASQUALIFIERTYPE 1002 /* UAObjectType */
#define UA_I4AAS_ID_AASREFERENCETYPE 1005 /* UAObjectType */
#define UA_I4AAS_ID_AASSUBMODELTYPE 1007 /* UAObjectType */
#define UA_I4AAS_ID_AASSUBMODELELEMENTTYPE 1008 /* UAObjectType */
#define UA_I4AAS_ID_AASPROPERTYTYPE 1009 /* UAObjectType */
#define UA_I4AAS_ID_AASSUBMODELELEMENTCOLLECTIONTYPE 1010 /* UAObjectType */
#define UA_I4AAS_ID_AASSUBMODELELEMENTORDEREDCOLLECTIONTYPE 1011 /* UAObjectType */
#define UA_I4AAS_ID_AASFILETYPE 1013 /* UAObjectType */
#define UA_I4AAS_ID_AASBLOBTYPE 1015 /* UAObjectType */
#define UA_I4AAS_ID_AASREFERENCEELEMENTTYPE 1016 /* UAObjectType */
#define UA_I4AAS_ID_AASRELATIONSHIPELEMENTTYPE 1017 /* UAObjectType */
#define UA_I4AAS_ID_OPERATIONVARIABLETYPE 1018 /* UAObjectType */
#define UA_I4AAS_ID_AASOPERATIONTYPE 1019 /* UAObjectType */
#define UA_I4AAS_ID_AASCONCEPTDICTIONARYTYPE 1020 /* UAObjectType */
#define UA_I4AAS_ID_AASVIEWTYPE 1022 /* UAObjectType */
#define UA_I4AAS_ID_AASASSETTYPE 1023 /* UAObjectType */
#define UA_I4AAS_ID_AASASSETADMINISTRATIONSHELLTYPE 1024 /* UAObjectType */
#define UA_I4AAS_ID_IAASIDENTIFIABLETYPE 2000 /* UAObjectType */
#define UA_I4AAS_ID_IAASREFERABLETYPE 2001 /* UAObjectType */
#define UA_I4AAS_ID_AASDATASPECIFICATIONTYPE 3000 /* UAObjectType */
#define UA_I4AAS_ID_AASDATASPECIFICATIONIEC61360TYPE 3001 /* UAObjectType */
#define UA_I4AAS_ID_AASREFERENCE 4000 /* UAReferenceType */
#endif /* UA_NODEIDS_I4AAS__H_ */ 
